name: Test

on:
  workflow_call:
    inputs:
      commit-ref:
        description: Commit ref to check out and run tests against.
        default: ''
        required: false
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
          stable: true

      - name: Test
        run: go test ./...